document.writeln("<div class=\'searchPage\'>");
document.writeln("  <div class=\'block\'>");
document.writeln("    <p onclick=\'foldSearch()\'>Close</p>");
document.writeln("    <li onclick=\'Search()\'>百度搜索</li>");
document.writeln("    <li onclick=\'Searen()\'>百度百科</li>");
document.writeln("    <li onclick=\'Searbil()\'>在哔哩哔哩中搜索</li>");
document.writeln("    <li onclick=\'Searwu()\'>无追搜索</li>");
document.writeln("    <li onclick=\'Searbi()\'>必应搜索</li>");
document.writeln("    <li onclick=\'Seardy()\'>在抖音中搜索</li>");
document.writeln("    <li onclick=\'Searkg()\'>在酷狗中搜索</li>");
document.writeln("    <li onclick=\'Searqy()\'>在QQ音乐中搜索</li>");
document.writeln("    <li onclick=\'Searncm()\'>在网易云音乐中搜索</li>");
document.writeln("");
document.writeln("  </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<div class=\'top\'>");
document.writeln("");
document.writeln("  <div class=\'letop\'>");
document.writeln("");
document.writeln("    <img class=\'itop\' src=\'images/Kryst.png\'/>");
document.writeln("    <h2 class=\'htop\'>Krystallos 主页</h2>");
document.writeln("");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\'rtop\'>");
document.writeln("    <ul class=\'utop\'>");
document.writeln("");
document.writeln("        <li class=\'ltop\'><a href=\'index.html\'>主页</a></li>");
document.writeln("        <li class=\'ltop\' onclick=\'page();\'>search</li>");
document.writeln("        <li class=\'ltop\'><a href=\'https://space.bilibili.com/1540895899\'>Bilibili</a></li>");
document.writeln("        <li class=\'ltop\'><a href=\'vise-index.html\'>Videos</a></li>");
document.writeln("        <li class=\'ltop\'><a href=\'krystab.html\'>Krystab</a></li>");
document.writeln("    </ul>");
document.writeln("");
document.writeln("  </div>");
document.writeln("");
document.writeln("</div>");